name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        cache: 'npm'

    - name: make setup
      run: make setup

    - name: make test
      run: make test

    - name: make lint
      run: make lint

    - uses: hexlet-components/hello-from-hexlet-action@release
